spring:
  packageScan: ['komics']
---
# log4j 配置文件路径
log4j.configuration:
  - file: ""
  - refreshInterval: 10
# 自定义的应用程序初始化监听器
application.initialize.listener: []
---
datasource:
  - name: "defaultDataSource"
    class: "com.alibaba.druid.pool.DruidDataSource"
    url: "jdbc:mysql://localhost:3306/komics?Unicode=true&characterEncoding=utf8&autoReconnect=true&failOverReadOnly=false"
    username: 'root'
    password: 'Qwer!234'
    minIdle: 5
    initialSize: 10
    maxActive: 100
