# Spring相关配置
spring:
  # Spring的自动扫描包
  packageScan: ['shenggu']
  # 如果要扩展spring的配置, 通过这里指定配置类
  configurationClasses: []
---
# 数据库配置: 如果有用到数据库,请打开数据源配置
database:
  # 数据源: 默认采用阿里巴巴的 druid data source, 暂不支持其他
  # TODO 支持多个数据源
  datasource:
    # 数据源名字
    name: "default"
    url: "jdbc:mysql://localhost:3306/decor_new"
    username: 'root'
    password: 'Qwer!234'
    minIdle: 5
    initialSize: 10
    maxActive: 100
    # 以下配置并不需要经常修改,可以保持为默认值
    maxWait: 60000
    testWhileIdle: true
    timeBetweenEvictionRunsMillis: 60000
    minEvictableIdleTimeMillis: 300000
    testOnBorrow: false
    testOnReturn: false
    poolPreparedStatements: true
    maxPoolPreparedStatementPerConnectionSize: 20
    filters: "wall,stat"
    validationQuery: "SELECT 'x'"
  # 数据库监控: 设置为 true 则打开 druid 的数据库监控配置
  monitor: true
# Ebean配置
ebean:
  # Ebean server配置
  #TODO 支持多个数据源
  server:
    datasource: "default"
    encryptKeyManager: "com.avaje.tests.basic.encrypt.BasicEncyptKeyManager"
    currentUserProvider: "com.avaje.ebean.MyCurrentUserProvider"
    cacheWarmingDelay: -1
    # ddl
    ddl.generate: true
    ddl.run: true
    #autotune.querytuning: true
    #autotune.profiling: true
    #autotune.profilingUpdateFrequency: 5
    #persistBatch: NONE
    #expressionNativeIlike: true
    #jsonInclude: NON_NULL
    # Ebean cluster config
    #cluster.type: mcast
    #cluster.mcast.listen.port: 9768
    #cluster.mcast.listen.address: 235.1.1.1
    #cluster.mcast.listen.disableLoopback: false
    #cluster.mcast.send.port: 9766
    #debug.remotetransaction: true
    #cluster.debuglevel: 1
    #uuidStoreAsBinary: true
    #transaction.rollbackOnChecked: false
    #migration.appName: myapp
    #migration.migrationPath: dbmigration/myapp
#---
# redis 配置,根据需要打开
# 默认使用Jedis
#redis:
#  # Jedis pool config
#  pool:
#    class: redis.clients.jedis.JedisPoolConfig
#    maxTotal:
#    maxIdle:
#    maxWaitMillis:
#    testOnBorrow:
#  #Jedis connection factory
#  connectionFactory:
#    usePool: true
#    hostName:
#    port:
#    password:
#    timeout:
#    database:
#---
# http client相关配置
#httpclient:
#  poolSize: 10