spring:
  packageScan: ['komics']
  configurationClasses: []
---
# 应用程序初始化监听器，用来执行定制化的初始化工作
#application.initialize.listener:
#  - a
#  - b
---
datasource:
  - name: "defaultDataSource"
    class: "com.alibaba.druid.pool.DruidDataSource"
    url: "jdbc:mysql://localhost:3306/komics?Unicode=true&characterEncoding=utf8&autoReconnect=true&failOverReadOnly=false"
    username: 'root'
    password: 'Qwer!234'
    minIdle: 5
    initialSize: 10
    maxActive: 100
