CREATE TABLE user(
  id BIGINT(11) PRIMARY KEY AUTO_INCREMENT,
  username VARCHAR(32) NOT NULL,
  password VARCHAR(32) NOT NULL,
  mobile VARCHAR(15) NOT NULL,
  email VARCHAR(32) NOT NULL,
  status VARCHAR(20) NOT NULL,
  version BIGINT(10) DEFAULT '1' NOT NULL,
  created TIMESTAMP DEFAULT 'CURRENT_TIMESTAMP' NOT NULL,
  modified TIMESTAMP DEFAULT 'CURRENT_TIMESTAMP' NOT NULL
);